NEPAL_DISTRICTS = [
    # Province 1 - Koshi
    {"name_nepali": "तापलेजुङ", "name_english": "Taplejung", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Phungling", "lat": 27.3500, "lon": 87.6667, "area_km2": 3646, "population": 127461, "flood_risk": 3, "landslide_risk": 5, "major_rivers": ["Tamur"], "dhm_stations": []},
    {"name_nepali": "संखुवासभा", "name_english": "Sankhuwasabha", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Khandbari", "lat": 27.3667, "lon": 87.2167, "area_km2": 3480, "population": 158742, "flood_risk": 3, "landslide_risk": 5, "major_rivers": ["Arun"], "dhm_stations": []},
    {"name_nepali": "सोलुखुम्बु", "name_english": "Solukhumbu", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Salleri", "lat": 27.5167, "lon": 86.5833, "area_km2": 3312, "population": 105886, "flood_risk": 2, "landslide_risk": 4, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "ओखलढुंगा", "name_english": "Okhaldhunga", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Okhaldhunga", "lat": 27.3083, "lon": 86.5028, "area_km2": 1074, "population": 147984, "flood_risk": 3, "landslide_risk": 4, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "खोटाङ", "name_english": "Khotang", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Diktel", "lat": 27.2167, "lon": 86.7833, "area_km2": 1591, "population": 206312, "flood_risk": 3, "landslide_risk": 4, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "भोजपुर", "name_english": "Bhojpur", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Bhojpur", "lat": 27.1667, "lon": 87.0500, "area_km2": 1507, "population": 182459, "flood_risk": 3, "landslide_risk": 5, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "धनकुटा", "name_english": "Dhankuta", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Dhankuta", "lat": 26.9833, "lon": 87.3333, "area_km2": 891, "population": 163412, "flood_risk": 3, "landslide_risk": 4, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "तेह्रथुम", "name_english": "Terhathum", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Myanglung", "lat": 27.1167, "lon": 87.5500, "area_km2": 679, "population": 100428, "flood_risk": 3, "landslide_risk": 4, "major_rivers": ["Tamor"], "dhm_stations": ["TM001"]},
    {"name_nepali": "पाँचथर", "name_english": "Panchthar", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Phidim", "lat": 27.1667, "lon": 87.7500, "area_km2": 1241, "population": 191817, "flood_risk": 3, "landslide_risk": 4, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "इलाम", "name_english": "Ilam", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Ilam", "lat": 26.9083, "lon": 87.9250, "area_km2": 1703, "population": 290254, "flood_risk": 3, "landslide_risk": 4, "major_rivers": ["Mechi", "Kankai"], "dhm_stations": []},
    {"name_nepali": "झापा", "name_english": "Jhapa", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Chandragadhi", "lat": 26.6500, "lon": 87.9833, "area_km2": 1606, "population": 812650, "flood_risk": 4, "landslide_risk": 1, "major_rivers": ["Mechi", "Kankai"], "dhm_stations": []},
    {"name_nepali": "मोरङ", "name_english": "Morang", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Biratnagar", "lat": 26.4525, "lon": 87.2718, "area_km2": 1855, "population": 967984, "flood_risk": 4, "landslide_risk": 1, "major_rivers": ["Kankai"], "dhm_stations": []},
    {"name_nepali": "सुनसरी", "name_english": "Sunsari", "province": 1, "province_name_nepali": "कोशी प्रदेश", "province_name_english": "Koshi Province", "hq": "Inaruwa", "lat": 26.5628, "lon": 87.1436, "area_km2": 1257, "population": 754777, "flood_risk": 5, "landslide_risk": 1, "major_rivers": ["Koshi"], "dhm_stations": ["KS001"]},
    # Province 2 - Madhesh
    {"name_nepali": "सप्तरी", "name_english": "Saptari", "province": 2, "province_name_nepali": "मधेश प्रदेश", "province_name_english": "Madhesh Province", "hq": "Rajbiraj", "lat": 26.5392, "lon": 86.7311, "area_km2": 1363, "population": 639284, "flood_risk": 5, "landslide_risk": 1, "major_rivers": ["Koshi"], "dhm_stations": []},
    {"name_nepali": "सिरहा", "name_english": "Siraha", "province": 2, "province_name_nepali": "मधेश प्रदेश", "province_name_english": "Madhesh Province", "hq": "Siraha", "lat": 26.6500, "lon": 86.2167, "area_km2": 1188, "population": 637560, "flood_risk": 5, "landslide_risk": 1, "major_rivers": ["Kamala"], "dhm_stations": []},
    {"name_nepali": "धनुषा", "name_english": "Dhanusa", "province": 2, "province_name_nepali": "मधेश प्रदेश", "province_name_english": "Madhesh Province", "hq": "Janakpur", "lat": 26.7267, "lon": 85.9236, "area_km2": 1180, "population": 754777, "flood_risk": 4, "landslide_risk": 1, "major_rivers": ["Kamala"], "dhm_stations": []},
    {"name_nepali": "महोत्तरी", "name_english": "Mahottari", "province": 2, "province_name_nepali": "मधेश प्रदेश", "province_name_english": "Madhesh Province", "hq": "Jaleshwar", "lat": 26.6500, "lon": 85.7667, "area_km2": 1002, "population": 627580, "flood_risk": 4, "landslide_risk": 1, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "सर्लाही", "name_english": "Sarlahi", "province": 2, "province_name_nepali": "मधेश प्रदेश", "province_name_english": "Madhesh Province", "hq": "Malangwa", "lat": 26.8583, "lon": 85.5628, "area_km2": 1259, "population": 769729, "flood_risk": 4, "landslide_risk": 1, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "रौतहट", "name_english": "Rautahat", "province": 2, "province_name_nepali": "मधेश प्रदेश", "province_name_english": "Madhesh Province", "hq": "Gaur", "lat": 26.7667, "lon": 85.2667, "area_km2": 1126, "population": 686722, "flood_risk": 4, "landslide_risk": 1, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "बारा", "name_english": "Bara", "province": 2, "province_name_nepali": "मधेश प्रदेश", "province_name_english": "Madhesh Province", "hq": "Kalaiya", "lat": 27.0333, "lon": 85.0000, "area_km2": 1190, "population": 756490, "flood_risk": 4, "landslide_risk": 1, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "पर्सा", "name_english": "Parsa", "province": 2, "province_name_nepali": "मधेश प्रदेश", "province_name_english": "Madhesh Province", "hq": "Birgunj", "lat": 27.0133, "lon": 84.8764, "area_km2": 1353, "population": 601017, "flood_risk": 3, "landslide_risk": 1, "major_rivers": [], "dhm_stations": []},
    # Province 3 - Bagmati (selected)
    {"name_nepali": "सिन्धुपाल्चोक", "name_english": "Sindhupalchowk", "province": 3, "province_name_nepali": "बागमती प्रदेश", "province_name_english": "Bagmati Province", "hq": "Chautara", "lat": 27.9803, "lon": 85.6897, "area_km2": 2542, "population": 287798, "flood_risk": 4, "landslide_risk": 5, "major_rivers": ["Sun Koshi", "Indrawati"], "dhm_stations": ["SK001"]},
    {"name_nepali": "काठमाडौं", "name_english": "Kathmandu", "province": 3, "province_name_nepali": "बागमती प्रदेश", "province_name_english": "Bagmati Province", "hq": "Kathmandu", "lat": 27.7172, "lon": 85.3240, "area_km2": 395, "population": 1744240, "flood_risk": 3, "landslide_risk": 2, "major_rivers": ["Bagmati"], "dhm_stations": ["BG001"]},
    {"name_nepali": "ललितपुर", "name_english": "Lalitpur", "province": 3, "province_name_nepali": "बागमती प्रदेश", "province_name_english": "Bagmati Province", "hq": "Patan", "lat": 27.6644, "lon": 85.3188, "area_km2": 385, "population": 468132, "flood_risk": 2, "landslide_risk": 2, "major_rivers": ["Bagmati"], "dhm_stations": []},
    {"name_nepali": "चितवन", "name_english": "Chitwan", "province": 3, "province_name_nepali": "बागमती प्रदेश", "province_name_english": "Bagmati Province", "hq": "Bharatpur", "lat": 27.6833, "lon": 84.4333, "area_km2": 2218, "population": 579984, "flood_risk": 4, "landslide_risk": 2, "major_rivers": ["Narayani"], "dhm_stations": ["NR001"]},
    {"name_nepali": "नुवाकोट", "name_english": "Nuwakot", "province": 3, "province_name_nepali": "बागमती प्रदेश", "province_name_english": "Bagmati Province", "hq": "Bidur", "lat": 27.9167, "lon": 85.1667, "area_km2": 1121, "population": 277471, "flood_risk": 3, "landslide_risk": 5, "major_rivers": ["Trishuli"], "dhm_stations": ["TR001"]},
    {"name_nepali": "धादिङ", "name_english": "Dhading", "province": 3, "province_name_nepali": "बागमती प्रदेश", "province_name_english": "Bagmati Province", "hq": "Dhadingbesi", "lat": 27.8667, "lon": 84.9000, "area_km2": 1926, "population": 336067, "flood_risk": 3, "landslide_risk": 5, "major_rivers": [], "dhm_stations": []},
    # Province 4 - Gandaki
    {"name_nepali": "कास्की", "name_english": "Kaski", "province": 4, "province_name_nepali": "गण्डकी प्रदेश", "province_name_english": "Gandaki Province", "hq": "Pokhara", "lat": 28.2096, "lon": 83.9856, "area_km2": 2017, "population": 492098, "flood_risk": 3, "landslide_risk": 5, "major_rivers": ["Seti"], "dhm_stations": []},
    {"name_nepali": "लमजुङ", "name_english": "Lamjung", "province": 4, "province_name_nepali": "गण्डकी प्रदेश", "province_name_english": "Gandaki Province", "hq": "Besisahar", "lat": 28.2333, "lon": 84.4167, "area_km2": 1692, "population": 167724, "flood_risk": 3, "landslide_risk": 5, "major_rivers": ["Marsyangdi"], "dhm_stations": ["MS001"]},
    {"name_nepali": "तनहुँ", "name_english": "Tanahun", "province": 4, "province_name_nepali": "गण्डकी प्रदेश", "province_name_english": "Gandaki Province", "hq": "Damauli", "lat": 27.9667, "lon": 84.3833, "area_km2": 1546, "population": 321932, "flood_risk": 3, "landslide_risk": 4, "major_rivers": ["Gandaki"], "dhm_stations": ["GD001"]},
    {"name_nepali": "स्याङ्जा", "name_english": "Syangja", "province": 4, "province_name_nepali": "गण्डकी प्रदेश", "province_name_english": "Gandaki Province", "hq": "Syangja", "lat": 28.0000, "lon": 83.8500, "area_km2": 1164, "population": 289148, "flood_risk": 3, "landslide_risk": 5, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "गोर्खा", "name_english": "Gorkha", "province": 4, "province_name_nepali": "गण्डकी प्रदेश", "province_name_english": "Gandaki Province", "hq": "Gorkha", "lat": 28.0000, "lon": 84.6333, "area_km2": 3610, "population": 271061, "flood_risk": 3, "landslide_risk": 5, "major_rivers": [], "dhm_stations": []},
    # Province 5 - Lumbini
    {"name_nepali": "रुपन्देही", "name_english": "Rupandehi", "province": 5, "province_name_nepali": "लुम्बिनी प्रदेश", "province_name_english": "Lumbini Province", "hq": "Butwal", "lat": 27.7006, "lon": 83.4532, "area_km2": 1360, "population": 880196, "flood_risk": 3, "landslide_risk": 2, "major_rivers": ["Tinau"], "dhm_stations": []},
    {"name_nepali": "दाङ", "name_english": "Dang", "province": 5, "province_name_nepali": "लुम्बिनी प्रदेश", "province_name_english": "Lumbini Province", "hq": "Ghorahi", "lat": 28.0333, "lon": 82.4833, "area_km2": 2955, "population": 552583, "flood_risk": 4, "landslide_risk": 3, "major_rivers": ["West Rapti"], "dhm_stations": ["RP001"]},
    {"name_nepali": "बाँके", "name_english": "Banke", "province": 5, "province_name_nepali": "लुम्बिनी प्रदेश", "province_name_english": "Lumbini Province", "hq": "Nepalgunj", "lat": 28.0528, "lon": 81.6172, "area_km2": 2337, "population": 491313, "flood_risk": 4, "landslide_risk": 1, "major_rivers": [], "dhm_stations": []},
    {"name_nepali": "बर्दिया", "name_english": "Bardiya", "province": 5, "province_name_nepali": "लुम्बिनी प्रदेश", "province_name_english": "Lumbini Province", "hq": "Gulariya", "lat": 28.2000, "lon": 81.3333, "area_km2": 2025, "population": 426576, "flood_risk": 5, "landslide_risk": 1, "major_rivers": ["Karnali", "Babai"], "dhm_stations": ["KR001"]},
    # Province 6 - Karnali
    {"name_nepali": "सुर्खेत", "name_english": "Surkhet", "province": 6, "province_name_nepali": "कर्णाली प्रदेश", "province_name_english": "Karnali Province", "hq": "Birendranagar", "lat": 28.6000, "lon": 81.6167, "area_km2": 2451, "population": 350804, "flood_risk": 3, "landslide_risk": 3, "major_rivers": [], "dhm_stations": []},
    # Province 7 - Sudurpashchim
    {"name_nepali": "कैलाली", "name_english": "Kailali", "province": 7, "province_name_nepali": "सुदूरपश्चिम प्रदेश", "province_name_english": "Sudurpashchim Province", "hq": "Dhangadhi", "lat": 28.6922, "lon": 80.5892, "area_km2": 3235, "population": 775709, "flood_risk": 5, "landslide_risk": 1, "major_rivers": ["Karnali"], "dhm_stations": []},
    {"name_nepali": "कञ्चनपुर", "name_english": "Kanchanpur", "province": 7, "province_name_nepali": "सुदूरपश्चिम प्रदेश", "province_name_english": "Sudurpashchim Province", "hq": "Mahendranagar", "lat": 28.9636, "lon": 80.1758, "area_km2": 1610, "population": 451248, "flood_risk": 5, "landslide_risk": 1, "major_rivers": [], "dhm_stations": []},
]

PROVINCES = [
    {"number": 1, "name_nepali": "कोशी प्रदेश", "name_english": "Koshi Province", "capital": "Biratnagar", "districts": 14, "population": 4534943},
    {"number": 2, "name_nepali": "मधेश प्रदेश", "name_english": "Madhesh Province", "capital": "Janakpur", "districts": 8, "population": 6107010},
    {"number": 3, "name_nepali": "बागमती प्रदेश", "name_english": "Bagmati Province", "capital": "Hetauda", "districts": 13, "population": 6095698},
    {"number": 4, "name_nepali": "गण्डकी प्रदेश", "name_english": "Gandaki Province", "capital": "Pokhara", "districts": 11, "population": 2479745},
    {"number": 5, "name_nepali": "लुम्बिनी प्रदेश", "name_english": "Lumbini Province", "capital": "Deukhuri", "districts": 12, "population": 5124220},
    {"number": 6, "name_nepali": "कर्णाली प्रदेश", "name_english": "Karnali Province", "capital": "Birendranagar", "districts": 10, "population": 1688775},
    {"number": 7, "name_nepali": "सुदूरपश्चिम प्रदेश", "name_english": "Sudurpashchim Province", "capital": "Dhangadhi", "districts": 9, "population": 2696501},
]